import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "./components/conditionalHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MusicShare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0f1a2b] w-screen min-h-screen`}
      >
        {/* Content wrapper */}
        <div className="flex flex-col items-center justify-start w-full pt-0 px-4">
          {/* CHANGED: pt-2 to pt-0 (removed all top padding) */}
          <ConditionalHeader />



          {/* Page content */}
          <div className="w-full flex flex-col items-center justify-start">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}